<!DOCTYPE html>
<html lang="en">
<head>
<!-- 2025-06-27T21:23:36Z -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>KDOC 205: エラーと例外の違いを見る</title>
<meta name="author" content="kijimaD" />
<meta name="generator" content="Org Mode" />
<link rel='shortcut icon' type='image/x-icon' href='https://kijimad.github.io/roam/favicon.ico' /><link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' media='print' onload='this.media="all"' /><link rel='stylesheet' href='https://kijimad.github.io/roam/css/site.css' /><link rel='stylesheet' href='https://kijimad.github.io/roam/css/code.css' /><link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin><link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+JP&display=swap' rel='stylesheet'>
</head>
<body>
<div id="preamble" class="status">
<div><div class="header"><div class="container"><div class="row"><div class="col-sm-12 col-md-12"><nav class="navbar navbar-light"/></div></div></div></div></div>
</div>
<div id="content" class="content">
<h1 class="title">KDOC 205: エラーと例外の違いを見る</h1>
<div id="outline-container-org73d2cd4" class="outline-2">
<h2 id="org73d2cd4"><a href="#org73d2cd4">この文書のステータス</a></h2>
<div class="outline-text-2" id="text-org73d2cd4">
<ul class="org-ul">
<li>作成
<ul class="org-ul">
<li class="on"><input type='checkbox' checked='checked' /> 2024-08-10 貴島</li>
</ul></li>
<li>レビュー
<ul class="org-ul">
<li class="on"><input type='checkbox' checked='checked' /> 2024-08-11 貴島</li>
</ul></li>
</ul>
</div>
</div>
<div id="outline-container-org02d99fe" class="outline-2">
<h2 id="org02d99fe"><a href="#org02d99fe">概要</a></h2>
<div class="outline-text-2" id="text-org02d99fe">
<p>
同僚との会話でエラーと例外は違う、という話が出た。違いを知らなかったので、調べた。
</p>

<p>
<a href="20210926100207-wikipedia.html#ID-39f0af27-f685-4ce5-beac-a3398f648ba4">Wikipedia</a>に、ちょうど説明している項目がある。
</p>

<blockquote>
<p>
例外(exception)はシステム担当者が問題解決を行う必要がある。例外の問題解決手段には例外を無視することも含まれるが、明確な根拠をもって無視する必要がある（設計の一環として一部の例外を無視しても問題ないと判断する，連携する他システムのメンテナンス中で例外発生が不可避な場合はメンテナンス完了を待つ）。例外に対して、ユーザーが解決すべき問題はエラー(error)と呼ぶ（但し、業務システム開発ではエラーを業務エラー、例外をシステムエラーと表現する場合もあり、技術者間での厳密な統一見解は存在しない）[1][2][3]。何らかのシステム開発を行う会社では、例外への対処が不適切であるとユーザーに損害を与えるため、システム障害を発生させるような例外発生は製品の瑕疵として扱う必要がある。
<a href="https://ja.wikipedia.org/wiki/%E4%BE%8B%E5%A4%96%E5%87%A6%E7%90%86">例外処理 - Wikipedia</a>
</p>
</blockquote>

<p>
わかったようなわからないような、という感じ。
</p>

<p>
<a href="20211007104541-java.html#ID-9fa3711b-a22e-4cf5-ae97-5c057083674a">Java</a>でいう例外とエラーは、また意味が異なるように見える。
</p>

<p>
最初に、エラー。
</p>

<blockquote>
<p>
ErrorはThrowableのサブクラスで、通常のアプリケーションであればキャッチ(cache)すべきではない重大な問題を示します。そうしたエラーの大部分は異常な状態です。
</p>

<p>
java.lang.Object
  java.lang.Throwable
    java.lang.Error
</p>

<p>
<a href="https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Error.html">Error (Java Platform SE 8 )</a>
</p>
</blockquote>

<p>
たとえば、<a href="https://docs.oracle.com/javase/jp/8/docs/api/java/lang/VirtualMachineError.html">VirtualMachineError</a>がある。Java仮想マシンが壊れているか、または動作を継続するのに必要なリソースが足りなくなったことを示す、という。たしかに重大な問題で、プログラムでキャッチしてもどうしようもなさそうだ。
</p>

<hr>

<p>
つぎに、例外。
</p>

<blockquote>
<p>
Exceptionクラスとそのサブクラスは、通常のアプリケーションでキャッチされる可能性のある状態を示すThrowableの形式の1つです。
</p>

<div class="org-src-container">
<pre class="src src-nil">java.lang.Object
  java.lang.Throwable
    java.lang.Exception
</pre>
</div>

<p>
<a href="https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Exception.html">Exception (Java Platform SE 8 )</a>
</p>
</blockquote>

<p>
たとえば<a href="https://docs.oracle.com/javase/jp/8/docs/api/java/lang/NullPointerException.html">NullPointerException</a>がある。オブジェクトが必要な場合に、アプリケーションがnullを使おうとするとスローされる、という。
</p>

<div class="org-src-container">
<label class="org-src-name"><span class="listing-number">Listing 1: </span>クラス構造</label><pre class="src src-nil">java.lang.Object
  java.lang.Throwable
    java.lang.Exception
      java.lang.RuntimeException
        java.lang.NullPointerException
</pre>
</div>

<p>
「エラー」に比べて、キャッチする余地があるのを感じる。
</p>

<p>
<a href="20211007104541-java.html#ID-9fa3711b-a22e-4cf5-ae97-5c057083674a">Java</a>でいうとそういう定義、というだけで、日常使っている「エラー」というともっと広い意味で、回復不能かどうかのニュアンスはないように見える。プログラムの実行が停止して目的を達成せず、何か文言が出ていたら「エラーだ」、という感じでつかっている。
</p>
</div>
</div>
<div id="outline-container-orgaf4c95f" class="outline-2">
<h2 id="orgaf4c95f"><a href="#orgaf4c95f">関連</a></h2>
<div class="outline-text-2" id="text-orgaf4c95f">
<p>
なし。
</p>
</div>
</div>
<div id="outline-container-org8ee00bd" class="outline-2">
<h2 id="org8ee00bd"><a href="#org8ee00bd">Backlinks</a></h2>
<div class="outline-text-2" id="text-org8ee00bd">
<ul class="org-ul">
<li><a href="./20240728T215234--kdoc-208-宣言と定義の違いを見る__wiki.html">KDOC 208: 宣言と定義の違いを見る</a></li>
</ul>
</div>
</div>
</div>
<div id="postamble" class="status">
<footer class="footer py-3"><div class="container"><div class="row "><div class="col-md-4"></div><div class="col-sm col-md"><nav class="navbar"><a class="nav-link text-secondary small px-0" href="./index.html">Insomnia</a><a class="nav-link text-secondary small px-0" href="./sitemap.html">Sitemap</a><a class="nav-link text-secondary small px-0" href="https://github.com/kijimaD/roam">Repository</a><a class="nav-link text-secondary small px-0" href="https://github.com/kijimaD">@kijimaD</a></nav></div><div class="col-md-4"></div></div></div></footer>
</div>
</body>
</html>
