<!DOCTYPE html>
<html lang="en">
<head>
<!-- 2025-09-09T09:27:10Z -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>KDOC 431: require.NoErrorを使ってエラー時に中断する</title>
<meta name="author" content="kijimaD" />
<meta name="generator" content="Org Mode" />
<link rel='shortcut icon' type='image/x-icon' href='https://kijimad.github.io/roam/favicon.ico' /><link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' media='print' onload='this.media="all"' /><link rel='stylesheet' href='https://kijimad.github.io/roam/css/site.css' /><link rel='stylesheet' href='https://kijimad.github.io/roam/css/code.css' /><link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin><link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+JP&display=swap' rel='stylesheet'>
</head>
<body>
<div id="preamble" class="status">
<div><div class="header"><div class="container"><div class="row"><div class="col-sm-12 col-md-12"><nav class="navbar navbar-light"/></div></div></div></div></div>
</div>
<div id="content" class="content">
<h1 class="title">KDOC 431: require.NoErrorを使ってエラー時に中断する</h1>
<div id="outline-container-org7530b3b" class="outline-2">
<h2 id="org7530b3b"><a href="#org7530b3b">この文書のステータス</a></h2>
<div class="outline-text-2" id="text-org7530b3b">
<ul class="org-ul">
<li>作成
<ul class="org-ul">
<li class="on"><input type='checkbox' checked='checked' /> 2025-09-05 貴島</li>
</ul></li>
<li>レビュー
<ul class="org-ul">
<li class="on"><input type='checkbox' checked='checked' /> 2025-09-05 貴島</li>
</ul></li>
</ul>
</div>
</div>
<div id="outline-container-orgfda3643" class="outline-2">
<h2 id="orgfda3643"><a href="#orgfda3643">概要</a></h2>
<div class="outline-text-2" id="text-orgfda3643">
<p>
<code>testify/assert</code> はGo言語でテスト用のアサーションヘルパーを提供するライブラリである。
</p>

<p>
よく使うものに、エラーをかんたんに検証できる、NoError()という関数がある。これには2つの種類がある。
</p>

<ul class="org-ul">
<li><code>require.NoError()</code> &#x2013; 失敗したらそのテストは中断する</li>
<li><code>assert.NoError()</code> &#x2013; 失敗してもそのテストを中断しない</li>
</ul>

<p>
というような違いがある。 <code>require</code> のほうは知らなかった。
</p>
</div>
</div>
<div id="outline-container-org2c2d4db" class="outline-2">
<h2 id="org2c2d4db"><a href="#org2c2d4db">関連</a></h2>
<div class="outline-text-2" id="text-org2c2d4db">
<p>
なし。
</p>
</div>
</div>
</div>
<div id="postamble" class="status">
<footer class="footer py-3"><div class="container"><div class="row "><div class="col-md-4"></div><div class="col-sm col-md"><nav class="navbar"><a class="nav-link text-secondary small px-0" href="./index.html">Insomnia</a><a class="nav-link text-secondary small px-0" href="./sitemap.html">Sitemap</a><a class="nav-link text-secondary small px-0" href="https://github.com/kijimaD/roam">Repository</a><a class="nav-link text-secondary small px-0" href="https://github.com/kijimaD">@kijimaD</a></nav></div><div class="col-md-4"></div></div></div></footer>
</div>
</body>
</html>
